name: Build and Test Elixir Library

on: [push, pull_request]

jobs:
  build-and-test:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: x86_64
          - os: macos-latest
            arch: aarch64
          - os: windows-latest
            arch: x86_64

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Elixir (Ubuntu)
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.15'
          otp-version: '26.0'
        env:
          ImageOS: ubuntu22

      - name: Set up Elixir (Windows)
        if: ${{ matrix.os == 'windows-latest' }}
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.15'
          otp-version: '26.0'
        env:
          ImageOS: win22

      - name: Set up Elixir (macOS)
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          brew update
          brew install elixir || brew upgrade elixir
          mix local.hex --force
          mix local.rebar --force

      - name: Install dependencies
        run: mix hex.build -o test_my_package --unpack

      - name: Run tests
        working-directory: ./test_crud_jt_package
        run: |
          mix deps.get
          mix compile
          mix test
