name: Build and Test Elixir Library

on: [push, pull_request]

jobs:
  build-and-test:
    strategy:
      matrix:
        include:
          #- os: ubuntu-latest
            #arch: x86_64
          - os: macos-latest
            arch: aarch64
          #- os: windows-latest
            #arch: x86_64

    runs-on: ${{ matrix.os }}

    steps:
      # Крок для отримання коду з репозиторію
      - uses: actions/checkout@v4


      # Налаштування середовища залежно від ОС
      - name: Set up Elixir (Ubuntu/Windows)
        if: ${{ matrix.os == 'ubuntu-latest' || matrix.os == 'windows-latest' }}
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.15' # Вкажіть потрібну версію Elixir
          otp-version: '26.0'    # Вкажіть відповідну версію OTP

      - name: Set up Elixir (macOS)
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          brew update
          brew install elixir || brew upgrade elixir

      # Встановлення залежностей
      - name: Install dependencies
        run: mix hex.build -o test_my_package --unpack

      # Запуск тестів
      - name: Run tests
        working-directory: ./test_crud_jt_package
        run: |
          mix deps.get
          mix compile
          mix test
